Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -22,13 +22,16 @@ jobs:
       run: dotnet restore
     - name: Build
       run: dotnet build --no-restore
-  test:
+  unit-test:
+    name: Test
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4         # checkout the repo
+      - uses: actions/checkout@v4     # checkout the repo
       - run: dotnet test --logger "trx;LogFileName=test-results.trx"
-      - uses: actions/upload-artifact@v4  # upload test results
-        if: success() || failure()        # run this step even if previous step failed
+      - name: Test Report
+        uses: dorny/test-reporter@v2
+        if: success() || failure()    # run this step even if previous step failed
         with:
-          name: test-results
-          path: ./KickStatsTests/TestResults/test-results.trx
+          name: NUnit Tests            # Name of the check run which will be created
+          path: KickStatsTests/TestResults/test-results.trx    # Path to test results
+          reporter: dotnet-trx        # Format of test results
